rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :authors
  get '/check.txt', to: proc {[200, {}, ['simple_check']]}
  resource :contact, only: %i[create]
  root to: "pages#home"

  resource :pages, path: '' do
    get :about
    get :work
  end

  resource :works do
    get :lettings
    get :schedule_gardener
  end
end

rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/app/models/article.rb
# frozen_string_literal: true

# Article
#  - informational post related to bcs
#
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 120 }
  validates :description, presence: true, length: { minimum: 5, maximum: 200 }
end

rails/app/models/author.rb
# frozen_string_literal: true

#
# Devise user model
#
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails/app/models/breadcrumb.rb
class Breadcrumb
  attr_reader :name, :path

  def initialize(name:, path: nil)
    @name = name
    @path = path
  end

  def link?
    @path.present?
  end
end

rails/app/models/contact.rb
# frozen_string_literal: true

# Contact
#  - wraps a contact form message
#    - validates
#    - data ready for mailer
#  - model without database
#
class Contact
  include ActiveModel::Model
  attr_accessor :name, :email, :message

  validates :name, presence: true, length: { minimum: 2, maximum: 100 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true, length: { minimum: 5, maximum: 2048 }
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :breadcrumbs

  def breadcrumbs
    @breadcrumbs ||= []
  end

  def add_breadcrumb(name:, path: nil)
    breadcrumbs << Breadcrumb.new(name: name, path: path)
  end
end

rails/app/controllers/contacts_controller.rb
# frozen_string_literal: true

# ContactsController
#  - management of Contact resource - email message
#
class ContactsController < ApplicationController
  def create
    @contact = Contact.new
    @contact.assign_attributes(contact_params)
    if @contact.valid?
      ContactMailer.contact_with(@contact).deliver_later
      flash[:notice] = "Your message has been sent!"
      redirect_to controller: "pages", action: "home"
    else
      render "pages/home"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

rails/app/controllers/pages_controller.rb
# frozen_string_literal: true

# PagesController
#  - responsible for the standard webpages
#    - home, about, contact etc
#
class PagesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def about; end

  def work; end
end

rails/app/controllers/works_controller.rb
# frozen_string_literal: true

# WorksController
#  - responsible for displaying work documentation
#    - different custom urls
#
class WorksController < ApplicationController
  before_action :set_breadcrumbs
  def lettings
    add_breadcrumb(name: "Lettings")
  end

  def schedule_gardener
    add_breadcrumb(name: "Schedule Gardener")
  end

  private

  def set_breadcrumbs
    add_breadcrumb(name: "Home", path: root_path)
    add_breadcrumb(name: "Work", path: work_pages_path)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, styles: "", title: nil)
    filename = "media/images/#{name}.svg"
    title ||= name.underscore.humanize
    inline_svg_pack_tag(filename, aria: true, nocomment: true, title: title, class: styles)
  end
end

rails/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

rails/app/views/contact/_form.html.erb
<%= form_with model: @contact, url: "/contact", class: 'w-11/12 md:w-5/6 lg:w-4/6 xl:w-1/2 2xl:w-1/3', local: true, validate: true  do |form| %>
<fieldset class='flex flex-col border-0 bg-gray-200 text-xl'>
  <h4 class='text-4xl pl-4 pt-12 border-b-2 border-gray-300'>Contact form</h4>

  <div class="flex flex-col mt-8 px-4">
    <%= form.label :name, class: '' %>
    <%= form.text_field :name, class: 'mt-2', autocorrect: 'off', required: true %>
  </div>

  <div class="flex flex-col mt-8 px-4">
    <%= form.label :email, class: '' %>
    <%= form.text_field :email, class: 'mt-2', autocorrect: 'off', autocapitalize: 'none', required: true %>
  </div>

  <div class="flex flex-col mt-8 px-4 c-form__highlight py-8">
    <%= render_svg "message", styles: 'w-32 h-14 justify-self-start' %>
    <%= form.label :message, class: '' %>
    <%= form.text_area :message, class: 'c-input-field-multiline mt-2', rows: 6 %>
  </div>

  <%= form.submit 'Contact', class: 'c-btn c-btn--secondary h-16 w-11/12 rounded self-center justify-self-center mt-8 mb-8' %>
</fieldset>
<% end %>

rails/app/views/layouts/_flashes.html.erb
<% flash.each do |state, message| %>
<div class="flash__message">
    <div class="flash__text notice"><%= flash[:notice] %></div>
    <div class="flash__icon"><%= render_svg "mini-ballon" %></div>
</div>
<% end %>

rails/app/views/layouts/_footer.html.erb
<footer class="footer bg-gray-800">
    <ul class="footer-nav grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 items-center justify-center my-8 text-2xl text-gray-200 no-underline">
        <li class="footer-nav__item pt-4">
            <%= render_svg "logo-dark-1", styles: 'logo h-24' %>
        </li>
        <li class="text-gray-200 text-center">
            <%= link_to "https://github.com/BCS-io", class: 'hover:text-white' do %>
              <div class="c-media">
                <div class="c-media__figure">
                  <%= render_svg "github", styles: 'logo h-16' %>
                </div>
                <div class="c-media__body">
                  BCS.io
                </div>
              </div>
            <% end %>
        </li>
        <li class="text-gray-200">
            <div class="c-media">
                <div class="c-media__figure">
                    <%= render_svg "location", styles: 'h-16' %>
                </div>
                <div class="c-media__body">
                    Business Consolidating Services<br>
                    Birmingham<br>
                    B75 6NR
                </div>
            </div>
        </li>
        <li class="text-gray-200">
            <%= link_to "mailto:hello@bcs.io", class: "hover:text-white" do %>
                <div class="c-media">
                    <div class="c-media__figure">
                        <%= render_svg "envelope", styles: 'h-16' %>
                    </div>
                    <div class="c-media__body">
                        hello@bcs.io
                    </div>
                </div>
            <% end %>
        </li>
    </ul>
    <p class="footer__copyright text-center text-gray-500 text-2xl">&copy; 2021 BCS Ltd. All rights reserved.&nbsp;<%= BcsIo::Application::VERSION %></p>
</footer>

rails/app/views/layouts/_main-header.html.erb
<header class="main-header flex flex-col justify-end">
    <div class="flex items-baseline justify-between flex-wrap">
        <%= link_to root_url,  class: 'relative', id: 'home-logo' do %>
            <h1 class="no-underline">
                <%= render_svg "logo", styles: 'h-14' %>
            </h1>
            <span class="text-gray-500 text-sm absolute -bottom-5 left-0">Business software</span>
        <% end %>

        <nav class="p-0 m-0">
            <ul class="flex m-0 p-0 text-lg sm:text-3xl active:underline p-0 m-0">
                <li class="p-0 ml-4">
                    <%= link_to_unless_current "About", about_pages_path, class: 'align-top' do %>
                      <span class= 'underline font-bold'>About</span>
                    <% end %>
                </li>
                <li class="p-0 ml-4 sm:ml-8">
                    <%= link_to_unless_current "Work", work_pages_path, class: '' do %>
                      <span class= 'underline font-bold'>Work</span>
                    <% end %>
                </li>
                <li class="p-0 ml-4 sm:ml-8"><%= link_to "Contact", root_path(anchor: "contact-us"), class: '' %></li>
            </ul>
        </nav>
    </div>
</header>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#fcc133">
    <meta name="msapplication-TileColor" content="#ffc40d">
    <meta name="theme-color" content="#FCC133">
  </head>

  <body class="application h-screen flex flex-col justify-between">
    <%= render 'layouts/flashes' %>
    <div class="wrapper">
      <%= render 'layouts/main-header' %>
    </div>
    <div class="wrapper flex-grow">
      <%= yield %>
    </div>
    <div class="bg-gray-800">
      <div class="wrapper">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

rails/app/views/pages/about.html.erb
<%= content_for :title, "About | BCS.io" %>

<div class="about">
  <div class="main text-xl max-w-2xl">
    <h1 class="heading-primary heading-primary--title">About</h1>

    <p class="mt-6">
      We are custom software developers, based in Birmingham using Open Software or Microsoft. Our team enjoys a challenge so tell us about your needs, however large or small.
    </p>

    <p class="mt-6">
      We keep listening and we keep refining until you're satisfied. We will work with you to get your ideas off the ground and flying.
    </p>
    <p class="mt-6">
      Open Source and Microsoft Software has been developed in a wide range of applications: E-commerce, accounting, retail, gardening and sports.
    </p>
    <p class="mt-6">
      Our team can manipulate and process multiple data sources in PostgresSQL, MySQl, SQL server, JSON API's, Excel spreadsheets or CSV to integrate smoothly into new software.
    </p>

    <p class="mt-6">
      Our aim is to provide the best possible software experience for our clients. We deliver a well integrated system with robust testing and comprehensive training and support. So speak to us soon.
    </p>
  </div>

  <div class="action mt-8">
    <%= link_to "Hire Us", root_path(anchor: "contact-us"), class: "c-btn c-btn--medium c-btn--action px-10 py-6 rounded" %>
  </div>

  <div class="skyline mt-8 h-30 w-full">
    <%= render_svg "city-skyline", styles: 'block' %>
  </div>
</div>

rails/app/views/pages/home.html.erb
<%= content_for :title, "BCS.io" %>

<div class="home">
  <main class="mt-4 flex flex-col justify-center max-w-md text-center text-2xl mx-auto">
    <h1>We create successful digital products by listening and talking to you</h1>
    <div class="mt-4">We work to understand your business and solve your problems. This allows us to create the best possible applications and allows you to meet your targets and create new business opportunities.</div>
  </main>

  <div class="idea-button mt-12">
    <%= link_to "Let's talk", root_path(anchor: "contact-us"), class: "c-btn c-btn--medium c-btn--action px-10 py-6 rounded" %>
  </div>

  <aside class="idea-picture mt-8">
    <%= render_svg "the-idea" %>
  </aside>

  <div class="knot mt-36 justify-self-center w-3/6 md:w-2/6 xl:w-3/12 2xl:w-1/6">
    <%= render_svg "knot" %>
  </div>

  <article class="mt-14 flex flex-col justify-center lg:h-screen max-w-md text-center text-2xl mx-auto">
      <h1>Solutions that take flight</h1>
      <span class="mt-4">Working with you and understanding your business we can develop your project quickly. We use robust review and testing procedures to ensure a speedy lift-off</span>
  </article>

  <aside class="solutions-picture mt-36">
    <%= render_svg "solutions-clouds" %>
    <%= render_svg "solutions-ballon" %>
  </aside>

  <div class="unknot mt-36 justify-self-center w-3/6 lg:w-5/12 xl:w-2/6">
    <%= render_svg "unknot" %>
  </div>

  <div class="contact-us-heading mt-36">
    <div class="ml-7 md:ml-14  lg:ml-44 xl:ml-72">
      <h1 class="heading-primary self-start">Explore</h1>
    </div>

    <div id="contact-us" class="contact-us flex justify-center">
      <%= render 'contact/form' %>
    </div>
  </div>

  <div class="hand-shake self-end justify-self-end h-120 max-w-xs mt-36 mb-6">
    <%= render_svg "hand-shake" %>
  </div>
</div>

rails/app/views/pages/work.html.erb
<%= content_for :title, "Work | BCS.io" %>

<div class="work">
  <div class="work-main">
    <h1 class="heading-primary heading-primary--title">Work</h1>

    <main class="mt-4 max-w-md text-center text-xl mx-auto">
      <div class="">We design advanced websites that are built around your customers' needs and your business goals.
We will collaborate closely throughout all stages of the project:  in design, implementation, testing, training and support.</div>
    </main>

    <section class="grid grid-cols-1 md:grid-cols-2 gap-x-2 gap-y-2 grid-rows-2 my-4">
      <figure class="bg-yellow-300 border-4 border-yellow-500 rounded">
        <%= link_to lettings_works_path, class: 'no-underline' do
          render_svg "adams-logo", styles: 'h-full w-full block test_letting '
        end %>
      </figure>

      <figure class="bg-red-300 border-4 border-red-500 rounded">
        <%= link_to "https://github.com/BCS-io/bcs.io" do
          render_svg "work/bcs_io/cover", styles: 'h-full w-full block test_bcs_io', title: 'BCS.io'
        end %>
      </figure>

      <figure class="bg-green-300 border-4 border-green-500 rounded">
        <%= link_to schedule_gardener_works_path, class: 'no-underline' do
          render_svg "works/schedule_gardener/leaf", styles: 'h-full w-full block test_leaf'
        end %>
      </figure>
    </section>
  </div>
</div>

rails/app/views/shared/_breadcrumbs.html.erb
<nav class="mt-6">
  <ol class="flex list-none text-gray-400">
    <% breadcrumbs.each do |crumb| %>
     <li>
      <% if crumb.link? %>
        <%= link_to crumb.name, crumb.path %>
      <% else %>
        <span>
          <%= crumb.name %>
        </span>
      <% end %>

      <% unless crumb == breadcrumbs.last %>
        <span>&nbsp;&raquo;&nbsp;</span>
      <% end %>
     </li>
    <% end %>
  </ol>
</nav>

rails/app/views/works/bcsio.html.erb
<h1>hello</h1>

rails/app/views/works/lettings.html.erb
<div class="page-content">
  <%= render "shared/breadcrumbs" %>
  <h1 class="text-4xl mt-6 mb-4">Lettings <span class="text-2xl text-gray-400">- Rental software</span></h1>
  <%= render_svg "works/lettings/logo", styles: 'gallery__img test_letting h-30 w-full' %>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div class="text-2xl">
      <p class="mt-4">Designing an accountancy or other complex program requires much detailed discussion to produce the best results. This was certainly true when we wrote software for a renting and letting company.</p>

      <p class="mt-4">We needed a flexible approach to deal with the different types of renting and service charges and the various due dates to create accurate invoices and account details. By understanding the client's requirements and giving a live system to try out we made sure they got what they wanted.</p>
    </div>
    <div class="text-2xl">
        <p class="mt-4">The time spent developing the robust testing paid off as the system has been maintained on supported versions of software without the client having downtime during upgrades.</p>
        <p class="mt-4">The developed software dealt seamlessly with the complexity of various starting and due dates, saving the client valuable time.
        Computerized invoices were successful in creating a more efficient payment return and the  detailed data available made for efficiencies in management control.</p>
    </div>
    <div class="mt-4">
      <%= image_pack_tag 'media/images/works/lettings/properties_index.jpg' %>
    </div>
    <div class="mt-4">
      <%= image_pack_tag 'media/images/works/lettings/property_show_maximized.jpg', class: '' %>
    </div>
  </div>
</div>

rails/app/views/works/schedule_gardener.html.erb
<div class="page-content">
  <%= render "shared/breadcrumbs" %>
  <h1 class="text-4xl mt-6">Schedule Gardener <span class="text-2xl text-gray-400">- Online booking</span></h1>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 my-4">
    <div class="text-2xl">
      <p class="mt-4">Unreliable British weather meant gardeners and their clients spent too much time on the phone booking and rebooking time slots.</p>

      <%= render_svg "works/schedule_gardener/leaf", styles: 'gallery__img test_letting h-20 w-full' %>

      <p class="mt-4">Moving to on line messaging and booking allowed more time for actual gardening, improving efficiency. With appointments easily visible any time slot mix-ups were eliminated creating client confidence. The system allowed the gardener to write up what work was done and schedule the work for the next visit particularly useful if the client was out.</p>
    </div>

    <div class="mt-4">
      <%= image_pack_tag 'media/images/works/schedule_gardener/demo_1.jpg' %>
    </div>

    <div class="mt-4 md:col-span-2">
      <%= image_pack_tag 'media/images/works/schedule_gardener/demo_2.jpg' %>
    </div>
  </div>
</div>